$color_active = rgb(268bd2)
$color_inactive = rgb(073642)
$color_shadow = rgba(002b36ee)

# ── Blur & Transparency ─────────────────────
$rounding = 10
$blur_size = 5
$blur_passes = 3
$active_opacity = 0.94
$inactive_opacity = 0.86
$dim_strength = 0.18
